language: objective-c
osx_image: xcode8.2

before_script:
  - bundle install
  - cd Bootstrap ; bundle exec pod install --repo-update ; cd ..
  - export LANG=en_US.UTF-8
script:
  - rake test
  - rake pod_lint
