language: objective-c
osx_image: xcode8.2

before_script:
  - bundle install
  - cd Bootstrap ; bundle exec pod install --repo-update ; cd ..
  - export LANG=en_US.UTF-8
script:
  - set -o pipefail
  - xcodebuild -workspace 'Bootstrap/Bootstrap.xcworkspace' -sdk 'iphonesimulator' -scheme 'Bootstrap' -destination "name=iPhone 6,OS=9.3" -destination "name=iPhone 6,OS=10.2" clean build test | xcpretty --color --simple
