name: Testing
on: [push, pull_request]

jobs:
  test:
    name: Testing Nimble-Snapshots
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.2.3
        with:
          xcode-version: 12

      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1.66.0
        with:
          ruby-version: 2.6
          bundler-cache: true

      - name: Run Danger
        run: bundle exec danger
      
      - name: Run tests in Swift 4.2
        run: xcodebuild -workspace 'Bootstrap/Bootstrap.xcworkspace' -sdk 'iphonesimulator' -scheme 'Bootstrap' -destination 'name=iPhone 8' SWIFT_VERSION=4.2 build test | tee output/xcodebuild_swift4.2.log | xcpretty --color --simple

      - name: Run tests in Swift 5.0
        run: xcodebuild -workspace 'Bootstrap/Bootstrap.xcworkspace' -sdk 'iphonesimulator' -scheme 'Bootstrap' -destination 'name=iPhone 8' SWIFT_VERSION=5.0 build test | tee output/xcodebuild_swift5.0.log | xcpretty --color --simple

      - name: Run Carthage integration test
        run: sh carthage-xcode-12.sh bootstrap --platform iOS && xcodebuild | xcpretty --color --simple
        shell: bash
      
      - name: Swiftlint
        run: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew install swiftlint
            swiftlint lint --no-cache --reporter junit | tee result.xml
